version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  discogs_service:
    build: backend/.
    restart: always
    env_file:
      - .env.backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: tone_addiction_frontend/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"

volumes:
  postgres_data:
